CREATE TABLE IF NOT EXISTS actuals
(
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_date        date,
    material_no        integer,
    ship_to_code       integer,
    chain_name         varchar(255),
    volume_units       integer,
    actual_sales_value float,
    promo              varchar(255),

    constraint actuals_fk foreign key (material_no, chain_name) references price (material_no, chain_name),
    constraint actuals_fk_prod foreign key (material_no) references products (material_id)
);

CREATE TABLE IF NOT EXISTS products
(
    material_id   integer,
    material_desc varchar(255),
    category_code integer,
    category_name varchar(255),

    constraint products_pk primary key (material_id)
);

CREATE TABLE IF NOT EXISTS customers
(
    ship_to_code integer,
    ship_to_name varchar(255),
    chain_name   varchar(255),

    constraint customers_pk primary key (ship_to_code)
);

CREATE TABLE IF NOT EXISTS price
(
    chain_name    varchar(255),
    material_no   integer,
    regular_price float,

    constraint price_pk primary key (chain_name, material_no)
);